version: 2.1

orbs:
    unity: game-ci/unity@1.3.0

workflows:
    # # Uncomment this job if you need to activate a PERSONAL license for Unity. We probably can create some kind of script to check if
    # # Unity is already activated and just execute this job if it isn't.
    # # For more information about activation, check: https://game.ci/docs/circleci/activation
     create-unity-activation-file:
         jobs:
             - unity/create-activation-file:
                 editor_version: <<pipeline.parameters.editor-version>>
    build:
        jobs:
            # # Run Tests
            # - unity/test:
            #     name: "editmode-tests"
            #     executor:
            #         name: <<pipeline.parameters.executor-name>>
            #         target_platform: <<pipeline.parameters.target-platform>>
            #         editor_version: <<pipeline.parameters.editor-version>>
            #     project-path: <<pipeline.parameters.project-path>>
            #     test-platform: "editmode"
            #     context: unity-personal
