version: 2.1

orbs:
    unity: game-ci/unity@1.3.0


workflows:
  create-unity-activation-file:
    jobs:
      - unity/create-activation-file
      # Windows Mono
      - unity/build:
          name: 'build-Windows64-mono'
          step-name: 'Build StandaloneWindows64'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/ubuntu'
            target_platform: 'windows-mono'
            editor_version: '2021.3.13f1'
            resource_class: 'large'
          project-path: 'Unity2D-Demo-Game-CI-CD/src'
          build-target: 'StandaloneWindows64'
          context: unity
      
